global-journeymap-config:
  journeymapEnabled: "true"
  useWorldId: "true"
  viewOnlyServerProperties: "true"
  allowMultiplayerSettings: "ALL"
  worldPlayerRadar: "ALL"
  worldPlayerRadarUpdateTime: "5"
  seeUndergroundPlayers: "ALL"
  hideOps: "false"
  hideSpectators: "false"
  allowDeathPoints: "true"
  showInGameBeacons: "true"
  allowWaypoints: "true"
  teleportEnabled: "false"
  renderRange: "0"
  surfaceMapping: "ALL"
  topoMapping: "ALL"
  biomeMapping: "ALL"
  caveMapping: "ALL"
  radarEnabled: "ALL"
  playerRadarEnabled: "true"
  villagerRadarEnabled: "true"
  animalRadarEnabled: "true"
  mobRadarEnabled: "true"
  configVersion: "5.9.15"
global-xaeros-config:
  caveMode: "true"
  netherCaveMode: "true"
  radar: "true"
global-voxel-config:
  enabled: "true"
default-world-config:
  enabled: 'true'
  teleportEnabled: 'false'
  renderRange: '0'
  surfaceMapping: "ALL"
  topoMapping:  "ALL"
  biomeMapping: "ALL"
  caveMapping: "ALL"
  radarEnabled: "ALL"
  playerRadarEnabled: 'true'
  villagerRadarEnabled: 'true'
  animalRadarEnabled: 'true'
  mobRadarEnabled: 'true'
  configVersion: "5.9.15"