name: Minimap-Control-Folia
main: net.edenor.minimap.MinimapPlugin
version: 1.1.0
api-version: 1.13
folia-supported: true
author: AltronMaxX
description: >
  Allows players to control how minimaps mods work per world.