name: Test build

on:
  push:
    branches: [ main ]

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew build
        env:
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build
